services:
  - type: web
    runtime: python
    name: visualisation_service
    repo: https://github.com/el-gif/Webapp
    numInstances: 1
    region: frankfurt
    plan: free
    branch: main
    buildCommand: conda env update -f environment.yml && pip install -r requirements.txt
    startCommand: python webapp.py  # Update to match your main file
    autoDeploy: true
