# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - windpower-webapp
name: Build and deploy Python app to Azure Web App - windpower-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
<<<<<<< HEAD:.github/workflows/main_windpower.yml
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_05C0B9F06D7D4B619EC8EFC5F783FAEA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_63333B40F45A43AEBE6FEE77D4CD9D27 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_99907B532B14414591949248C5C94105 }}
=======
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B74CB773730B47FC87C75B77BD0ECE6B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F582A057DA224481BBDAF3E51EA4C983 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_505B25F529F440BDB6C34589AB185C56 }}
>>>>>>> 3bcd7a614cbe5e73b6bb02df283594e8b3dd01fb:.github/workflows/main_windpower-webapp.yml

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'windpower-webapp'
          app-name: 'windpower-webapp'
          slot-name: 'Production'
          